apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
  labels:
    app: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-docker-app-container
        image: ml-docker-app:latest  # Ensure this is the correct local image name
        imagePullPolicy: Never  # Prevent Kubernetes from pulling from a registry
        ports:
        - containerPort: 5000
