# this file is used to run the Airflow web server with a single Docker command, 
#using Docker Compose is recommended because it simplifies the management of multiple services (like the scheduler and web server) and their configurations.
# ensure to have command command: ["bash", "-c", "airflow db init && airflow webserver"] to initialize database

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
  
  webserver:
    image: apache/airflow:latest
    
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__API__AUTH_BACKEND=airflow.auth.backends.basic
    ports:
      - "8080:8080"
    command: ["bash", "-c", "airflow db init && airflow webserver "]
  
  scheduler:
    image: apache/airflow:latest
    depends_on:
      - postgres
    command: ["bash", "-c", "airflow db init && airflow scheduler"]
