

name: git actions   #name of this workflow
on:
    push:
      branches:
        - master  # Trigger the workflow only on push to 'master' branch
  
jobs:
  building:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python version 3.12 and enable pip caching
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Cache pip dependencies for faster builds

      # Step 3: Install dependencies from requirements.txt
      - run: pip install -r requirements.txt
      - run: python unittesting.py
